services:
  mysql:
    image: mysql:8.0
    container_name: examme_db
    restart: always
    environment:
      MYSQL_DATABASE: examme_db
      MYSQL_ROOT_PASSWORD: asiman2006M
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: examme-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/examme_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: asiman2006M
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data: